language: r

sudo: required
bioc_required: true

apt_packages:
 - libnetcdf-dev
 - udunits-bin
 - libudunits2-dev

r_binary_packages:
 - RUnit
 - testthat

bioc_packages:
 - mzR

notifications:
  email:
    on_success: change
    on_failure: change