language: c

services:
  - docker

before_install:
  - curl -OL http://raw.github.com/jasenfinch/dotfiles/master/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo apt-get install -y libnetcdf-dev udunits-bin libudunits2-dev

install:
  - ./travis-tool.sh install_bioc_deps

script: 
  - ./travis-tool.sh run_tests

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - git clone https://github.com/jasenfinch/HRM-docker.git
  - docker build -t jasenfinch/hrm-docker ./HRM-docker
  - docker push jasenfinch/hrm-docker

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change