language: r

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: true

r:
 - release
 - devel

apt_packages:
 - libnetcdf-dev
 - udunits-bin
 - libudunits2-dev
 - netcdf-bin
 - ffmpeg
 - cargo

r_binary_packages:
 - RUnit
 - testthat

r_packages:
 - rlang
 - digest
 - devtools

bioc_packages:
 - mzR

after_success:
 - Rscript -e 'covr::codecov()'
    
notifications:
  email:
    on_success: change
    on_failure: change