language: r
sudo: required
bioc_required: true

r_binary_packages:
 - RUnit
 - testthat

bioc_packages:
 - mzR
	
# Install the bleeding edge version of a package from github (eg to pick
# up a not-yet-released bugfix)
r_github_packages:
 - jasenfinch/OrbiFIEproc