language: r

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: true

r:
 - release
 - devel

apt_packages:
 - libnetcdf-dev
 - udunits-bin
 - libudunits2-dev
 - netcdf-bin
 - ffmpeg
 - cargo

after_success:
 - Rscript -e 'covr::codecov()'
    
notifications:
  email:
    on_success: change
    on_failure: change