language: r

services:
 - docker

sudo: required
bioc_required: true

apt_packages:
 - libnetcdf-dev
 - udunits-bin
 - libudunits2-dev

r_binary_packages:
 - RUnit
 - testthat

bioc_packages:
 - mzR

r_github_packages:
 - jasenfinch/OrbiFIEproc

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - git clone https://github.com/jasenfinch/HRM-docker.git
  - docker build -t jasenfinch/hrm-docker ./HRM-docker
  - docker push jasenfinch/hrm-docker

notifications:
  email:
    on_success: change
    on_failure: change