# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_binneR_wrappers", use_symbols = TRUE, package_name = "binneR")

#' @docType package
#' @usage NULL
#' @useDynLib binneR, .registration = TRUE
NULL

parse_mzml <- function(path) .Call(wrap__parse_mzml, path)


# nolint end
